wdl2cwl/main.py, wdl2cwl/tests/cwl_files/seqtk.cwl, wdl2cwl/tests/cwl_files/smoove.cwl, wdl2cwl/tests/test_cwl.py, wdl2cwl/tests/wdl_files/seqtk.wdl
Handle bound inputs
Convert int, boolean type values of bound inputs from string to their respective type.
=> Handle bound inputs

wdl2cwl/main.py, wdl2cwl/tests/cwl_files/smoove.cwl, wdl2cwl/tests/wdl_files/smoove.wdl
Handle string concatenations in the output section
=> Wdl outputs

wdl2cwl/main.py, wdl2cwl/tests/cwl_files/CollectQualityYieldMetrics.cwl, wdl2cwl/tests/cwl_files/smoove.cwl, wdl2cwl/tests/wdl_files/smoove.wdl
Added WDL requirement time minutes.
Modified docker and memory requirement to get the value from bound inputs in case the requirements are not defined in the requirements section as a string.
=> Handle WDL requirements

wdl2cwl/main.py, wdl2cwl/tests/cwl_files/seqtk.cwl, wdl2cwl/tests/wdl_files/seqtk.wdl
=> Handle expression placeholder true and false

wdl2cwl/main.py, wdl2cwl/tests/cwl_files/CollectQualityYieldMetrics.cwl, wdl2cwl/tests/cwl_files/smoove.cwl
Add js function to handle memory requirements
=> Change memory requirement

wdl2cwl/main.py, wdl2cwl/tests/cwl_files/hisat2.cwl, wdl2cwl/tests/test_cwl.py, wdl2cwl/tests/wdl_files/hisat2.wdl
~~#34 is addressed here~~
Fixes #34 
(Writing it this was means that merging this PR will close that issue)
=> Handle array inputs

wdl2cwl/main.py, wdl2cwl/tests/cwl_files/CollectReadgroupBamQualityMetrics.cwl, wdl2cwl/tests/cwl_files/hisat2_1.cwl, wdl2cwl/tests/cwl_files/hisat2_2.cwl, wdl2cwl/tests/test_cwl.py, wdl2cwl/tests/wdl_files/CollectQualityYieldMetrics.wdl, wdl2cwl/tests/wdl_files/CollectReadgroupBamQualityMetrics.wdl, wdl2cwl/tests/wdl_files/hisat2_1.wdl, wdl2cwl/tests/wdl_files/hisat2_2.wdl, wdl2cwl/tests/wdl_files/seqtk.wdl, wdl2cwl/tests/wdl_files/smoove.wdl
New test file gave an error for expression placeholder option 'true and false'. Modified code to address that issue.
Added missing source permalinks to the test WDL files.
=> Add new test file

wdl2cwl/main.py, wdl2cwl/tests/cwl_files/TrimAdapters.cwl, wdl2cwl/tests/test_cwl.py, wdl2cwl/tests/wdl_files/TrimAdapters.wdl
New test case has been added.
Modified code for wdl outputs
=> Modify Wdl output

wdl2cwl/main.py, wdl2cwl/tests/cwl_files/rtg_2.cwl, wdl2cwl/tests/test_cwl.py, wdl2cwl/tests/wdl_files/rtg_2.wdl
Modified code to handle WDL commands given with the syntax ```command <<<......>>>```
Added new test case.
=> Modify command

wdl2cwl/main.py, wdl2cwl/tests/cwl_files/vardict.cwl, wdl2cwl/tests/test_cwl.py, wdl2cwl/tests/wdl_files/vardict.wdl
Handle CPU requirements with integer additions.
Added new test case.
=> Modify CPU requirement

wdl2cwl/main.py, wdl2cwl/tests/cwl_files/UmiCorrection.cwl, wdl2cwl/tests/wdl_files/UmiCorrection.wdl
Handle outputs with placeholder style ${}
=> Modify outputs

wdl2cwl/tests/cwl_files/UmiCorrection.cwl, wdl2cwl/tests/cwl_files/vardict.cwl, wdl2cwl/tests/wdl_files/UmiCorrection.wdl, wdl2cwl/tests/wdl_files/vardict.wdl
Test files have been modified with the newly added features
=> Modify test files

wdl2cwl/main.py, wdl2cwl/tests/cwl_files/vardict.cwl
Fixed conversion of float inputs that were converted to a string previously
=> Handle float inputs

wdl2cwl/main.py, wdl2cwl/tests/cwl_files/transcriptclean_1.cwl, wdl2cwl/tests/test_cwl.py, wdl2cwl/tests/wdl_files/transcriptclean_1.wdl
=> Handle stdout() in outputs

requirements.txt, setup.py, wdl2cwl/main.py, wdl2cwl/tests/cwl_files/CollectReadgroupBamQualityMetrics.cwl, wdl2cwl/tests/cwl_files/UmiCorrection.cwl, wdl2cwl/tests/cwl_files/bowtie_1.cwl, wdl2cwl/tests/cwl_files/bowtie_2.cwl, wdl2cwl/tests/cwl_files/deepvariant.cwl, wdl2cwl/tests/cwl_files/gatk_1.cwl, wdl2cwl/tests/cwl_files/hisat2_1.cwl, wdl2cwl/tests/cwl_files/hisat2_2.cwl, wdl2cwl/tests/cwl_files/isoseq3.cwl, wdl2cwl/tests/cwl_files/pbmm2.cwl, wdl2cwl/tests/cwl_files/rtg.cwl, wdl2cwl/tests/cwl_files/rtg_2.cwl, wdl2cwl/tests/cwl_files/seqtk.cwl, wdl2cwl/tests/cwl_files/smoove.cwl, wdl2cwl/tests/cwl_files/transcriptclean_1.cwl, wdl2cwl/tests/cwl_files/vardict.cwl, wdl2cwl/tests/cwl_files/vt.cwl
=> javascript: use dot notation when possible

wdl2cwl/main.py, wdl2cwl/tests/cwl_files/minCores.cwl, wdl2cwl/tests/test_cwl.py, wdl2cwl/tests/wdl_files/minCores.wdl
=> Translate runtime cpu into coresMin even when string provided

README.md
Closes #108
- add more test options for tox in the `README`
=> add more tox tests options to the docs

wdl2cwl/main_oop.py, wdl2cwl/tests/cwl_tests.yaml, wdl2cwl/tests/oop_cwl_files/validateOptimus_1.cwl, wdl2cwl/tests/oop_cwl_files/validateOptimus_2.cwl, wdl2cwl/tests/test_miniwdl.py
Add functionalities to handle validateOptimus_1.wdl and validateOptimus_2.wdl
=> Adopting the validateOptimus files

README.md
Small PR before calling it a day :sleeping_bed: 
I think we recently changed the minimum Python version to 3.7.
=> Update minimum Python in readme

wdl2cwl/main_oop.py, wdl2cwl/tests/oop_cwl_files/TrimAdapters.cwl, wdl2cwl/tests/oop_cwl_files/UmiCorrection.cwl, wdl2cwl/tests/oop_cwl_files/seqtk_1.cwl, wdl2cwl/tests/oop_cwl_files/seqtk_2.cwl, wdl2cwl/tests/oop_cwl_files/validateOptimus_3.cwl
=> fix indentation in command string

wdl2cwl/main.py, wdl2cwl/tests/cwl_files/bcftools.cwl, wdl2cwl/tests/cwl_files/rtg_2_tasks.cwl, wdl2cwl/tests/test_cwl.py, wdl2cwl/tests/wdl_files/bcftools.wdl, wdl2cwl/tests/wdl_files/rtg_2_tasks.wdl
closes #67
Handle multiple tasks in one file using $graph.
=> add graph for multiple tasks

mypy.ini, mypy_requirements.txt
and clean up the configuration
=> Pin the mypy version

.github/workflows/ci-tests.yml, tox.ini, wdl2cwl/main.py
=> Refactor get_cwl_task_outputs()

wdl2cwl/main.py, wdl2cwl/tests/cwl_files/FunctionalEquivalence.cwl, wdl2cwl/tests/cwl_files/InternalTasks.cwl, wdl2cwl/tests/cwl_files/read_boolean.cwl, wdl2cwl/tests/test_cwl.py, wdl2cwl/tests/wdl_files/FunctionalEquivalence.wdl
print warning but don't break if we are unable to extract a static
docker name
Fixes #178
=> read_{tsv,int} ; added more stdout support

wdl2cwl/main.py, wdl2cwl/tests/cwl_files/FunctionalEquivalence.cwl, wdl2cwl/tests/cwl_files/InternalTasks.cwl, wdl2cwl/tests/cwl_files/Qc.cwl, wdl2cwl/tests/cwl_files/align_and_count.cwl, wdl2cwl/tests/cwl_files/align_and_count_multiple_report.cwl, wdl2cwl/tests/cwl_files/bowtie.cwl, wdl2cwl/tests/cwl_files/bwa.cwl, wdl2cwl/tests/cwl_files/deepvariant.cwl, wdl2cwl/tests/cwl_files/gatk.cwl, wdl2cwl/tests/cwl_files/gwas.cwl, wdl2cwl/tests/cwl_files/hisat2.cwl, wdl2cwl/tests/cwl_files/literal_test.cwl, wdl2cwl/tests/cwl_files/read_string_cornercase.cwl, wdl2cwl/tests/cwl_files/rtg.cwl, wdl2cwl/tests/cwl_files/transcriptclean.cwl, wdl2cwl/tests/cwl_files/vardict.cwl, wdl2cwl/tests/cwl_files/whatshap.cwl, wdl2cwl/tests/test_cwl.py, wdl2cwl/tests/wdl_files/read_string_cornercase.wdl, wdl2cwl/tests/wdl_files/whatshap.wdl
=> Fix quoting & Add another example of if-then-else

wdl2cwl/main.py, wdl2cwl/tests/cwl_files/FunctionalEquivalence.cwl, wdl2cwl/tests/cwl_files/Utilities.cwl, wdl2cwl/tests/cwl_files/pacbio.cwl, wdl2cwl/tests/cwl_tests.yaml, wdl2cwl/tests/inputs/Utilities_CreateSequenceGroupingTSV.yaml, wdl2cwl/tests/inputs/pacbio_ccsChunks.yaml, wdl2cwl/tests/test_cwl.py, wdl2cwl/tests/wdl_files/Utilities.wdl, wdl2cwl/tests/wdl_files/pacbio.wdl
also fix read_tsv() and add functional test
Fixes #175
=> implement read_lines() with a functional test

README.md, wdl2cwl/main.py, wdl2cwl/tests/cwl_files/FunctionalEquivalence.cwl, wdl2cwl/tests/cwl_files/InternalTasks.cwl, wdl2cwl/tests/cwl_files/Qc.cwl, wdl2cwl/tests/cwl_files/Utilities.cwl, wdl2cwl/tests/cwl_files/bowtie.cwl, wdl2cwl/tests/cwl_files/bwa.cwl, wdl2cwl/tests/cwl_files/deepvariant.cwl, wdl2cwl/tests/cwl_files/gatk.cwl, wdl2cwl/tests/cwl_files/hisat2.cwl, wdl2cwl/tests/cwl_files/merge_svs.cwl, wdl2cwl/tests/cwl_files/placeholder_options_test.cwl, wdl2cwl/tests/cwl_files/vardict.cwl, wdl2cwl/tests/cwl_files/whatshap.cwl, wdl2cwl/tests/cwl_tests.yaml, wdl2cwl/tests/test_cwl.py, wdl2cwl/tests/wdl_files/placeholder_options_test.wdl
Fixes #114 
- `defined()` now works outside of WDL Placeholder strings
- `default` as a placeholder string option is now implemented
=> improve handling of placeholder options

wdl2cwl/main.py, wdl2cwl/tests/cwl_files/BuildIndices.cwl, wdl2cwl/tests/cwl_files/struct_output.cwl, wdl2cwl/tests/cwl_tests.yaml, wdl2cwl/tests/inputs/struct_output.yaml
- fix the expression used by the output valueFrom hack
- add StepInputExpressionRequirement for valueFrom outputs
=> Fixes for output valueFrom due to outputs that pull from structs

README.md, wdl2cwl/main.py, wdl2cwl/tests/cwl_files/basic_quote.cwl, wdl2cwl/tests/cwl_files/basic_sep.cwl, wdl2cwl/tests/cwl_tests.yaml, wdl2cwl/tests/inputs/basic_sep.inputs.yaml, wdl2cwl/tests/test_cwl.py, wdl2cwl/tests/wdl_files/basic_quote.wdl, wdl2cwl/tests/wdl_files/basic_sep.wdl
- Improve error messages for unhandled type
- support the `Any` WDL type
- implement `quote()`
- skip synthentic placeholder `_runtime` nodes
- `sep()`: allow dynamic expression for separation item
=> wdl conf tests 01
